//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorLocalization() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EditorLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Bold 的當地語系化字串。
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert hyperlink 的當地語系化字串。
        /// </summary>
        internal static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete {0}? 的當地語系化字串。
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A directory with this name was not found. 的當地語系化字串。
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Empty Folder 的當地語系化字串。
        /// </summary>
        internal static string EmptyFolder {
            get {
                return ResourceManager.GetString("EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select font family 的當地語系化字串。
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (inherited font) 的當地語系化字串。
        /// </summary>
        internal static string FontNameInherit {
            get {
                return ResourceManager.GetString("FontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select font size 的當地語系化字串。
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (inherited size) 的當地語系化字串。
        /// </summary>
        internal static string FontSizeInherit {
            get {
                return ResourceManager.GetString("FontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select block type 的當地語系化字串。
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Indent 的當地語系化字串。
        /// </summary>
        internal static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert 的當地語系化字串。
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert HTML 的當地語系化字串。
        /// </summary>
        internal static string InsertHtml {
            get {
                return ResourceManager.GetString("InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert image 的當地語系化字串。
        /// </summary>
        internal static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert ordered list 的當地語系化字串。
        /// </summary>
        internal static string InsertOrderedList {
            get {
                return ResourceManager.GetString("InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert unordered list 的當地語系化字串。
        /// </summary>
        internal static string InsertUnorderedList {
            get {
                return ResourceManager.GetString("InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The selected file {0} is not valid. Supported file types are {1}. 的當地語系化字串。
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Italic 的當地語系化字串。
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Center text 的當地語系化字串。
        /// </summary>
        internal static string JustifyCenter {
            get {
                return ResourceManager.GetString("JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Justify 的當地語系化字串。
        /// </summary>
        internal static string JustifyFull {
            get {
                return ResourceManager.GetString("JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Align text left 的當地語系化字串。
        /// </summary>
        internal static string JustifyLeft {
            get {
                return ResourceManager.GetString("JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Align text right 的當地語系化字串。
        /// </summary>
        internal static string JustifyRight {
            get {
                return ResourceManager.GetString("JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open link in new window 的當地語系化字串。
        /// </summary>
        internal static string OpenInNewWindow {
            get {
                return ResourceManager.GetString("OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 or 的當地語系化字串。
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Arrange by: 的當地語系化字串。
        /// </summary>
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        internal static string OrderByName {
            get {
                return ResourceManager.GetString("OrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size 的當地語系化字串。
        /// </summary>
        internal static string OrderBySize {
            get {
                return ResourceManager.GetString("OrderBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Outdent 的當地語系化字串。
        /// </summary>
        internal static string Outdent {
            get {
                return ResourceManager.GetString("Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A file with name {0} already exists in the current directory. Do you want to overwrite it? 的當地語系化字串。
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Strikethrough 的當地語系化字串。
        /// </summary>
        internal static string Strikethrough {
            get {
                return ResourceManager.GetString("Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Styles 的當地語系化字串。
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tooltip 的當地語系化字串。
        /// </summary>
        internal static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Underline 的當地語系化字串。
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove hyperlink 的當地語系化字串。
        /// </summary>
        internal static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload 的當地語系化字串。
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Web address 的當地語系化字串。
        /// </summary>
        internal static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
    }
}
