//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0731Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpDb()
        {
            this.MacInvDbs = new HashSet<MacInvDb>();
        }
    
        public string Account { get; set; }
        public int EmployeeID { get; set; }
        public string UserName { get; set; }
        public string PhoneNum { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Birthday { get; set; }
        public string AddDate { get; set; }
        public string UpdateTime { get; set; }
        public Nullable<int> Permission { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> Assignment { get; set; }
        public string MachineId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MacInvDb> MacInvDbs { get; set; }
    }
}
