//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0731Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemDb()
        {
            this.WarehouseDbs = new HashSet<WarehouseDb>();
        }
    
        public int ItemId { get; set; }
        public string ItemImg { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemUnitPrice { get; set; }
        public string Class { get; set; }
        public string Calorles { get; set; }
        public string Protein { get; set; }
        public string Carbohydrate { get; set; }
        public string Fat { get; set; }
        public string Sugars { get; set; }
        public string Sodium { get; set; }
        public string Capacity { get; set; }
        public string Slogan1 { get; set; }
        public string Slogen2 { get; set; }
        public string PayUrl { get; set; }
        public string ImgUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseDb> WarehouseDbs { get; set; }
    }
}
