//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0731Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacInvDb
    {
        public int DataNo { get; set; }
        public string MachineId { get; set; }
        public string Account { get; set; }
        public Nullable<int> ItemId_DataNo { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual EmpDb EmpDb { get; set; }
        public virtual MachineDb MachineDb { get; set; }
        public virtual WarehouseDb WarehouseDb { get; set; }
    }
}
