//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0731Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseDb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseDb()
        {
            this.MacInvDbs = new HashSet<MacInvDb>();
        }
    
        public int DataNo { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
    
        public virtual ItemDb ItemDb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MacInvDb> MacInvDbs { get; set; }
    }
}
